package beam.aws.rds;

import beam.core.BeamException;
import beam.core.diff.ResourceDiffProperty;
import beam.core.diff.ResourceName;
import beam.lang.Resource;
import com.psddev.dari.util.ObjectUtils;
import software.amazon.awssdk.services.rds.RdsClient;
import software.amazon.awssdk.services.rds.model.CreateEventSubscriptionResponse;
import software.amazon.awssdk.services.rds.model.DescribeEventSubscriptionsResponse;
import software.amazon.awssdk.services.rds.model.SubscriptionNotFoundException;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

@ResourceName("db-event-subscription")
public class DbEventSubscriptionResource extends RdsTaggableResource {

    private Boolean enabled;
    private List<String> eventCategories;
    private String snsTopicArn;
    private List<String> sourceIds;
    private String sourceType;
    private String subscriptionName;

    /**
     * Indicate whether to activate the subscription.
     */
    @ResourceDiffProperty(updatable = true)
    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * A list of event categories for a SourceType that you want to subscribe to. You can see a list of the categories for a given SourceType in the `Events <https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html>`_ topic in the Amazon RDS User Guide or by using the `DescribeEventCategories` action.
     */
    @ResourceDiffProperty(updatable = true)
    public List<String> getEventCategories() {
        if (eventCategories == null || eventCategories.isEmpty()) {
            return new ArrayList<>();
        }

        List<String> sorted = new ArrayList<>(eventCategories);
        Collections.sort(sorted);

        return sorted;
    }

    public void setEventCategories(List<String> eventCategories) {
        this.eventCategories = eventCategories;
    }

    /**
     * The Amazon Resource Name (ARN) of the SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it. (Required)
     */
    @ResourceDiffProperty(updatable = true)
    public String getSnsTopicArn() {
        return snsTopicArn;
    }

    public void setSnsTopicArn(String snsTopicArn) {
        this.snsTopicArn = snsTopicArn;
    }

    /**
     * The list of identifiers of the event sources for which events are returned. If not specified, then all sources are included in the response. An identifier must begin with a letter and must contain only ASCII letters, digits, and hyphens; it can't end with a hyphen or contain two consecutive hyphens.
     */
    public List<String> getSourceIds() {
        return sourceIds;
    }

    public void setSourceIds(List<String> sourceIds) {
        if (sourceIds == null) {
            sourceIds = new ArrayList<>();
        }

        this.sourceIds = sourceIds;
    }

    /**
     * The type of source that is generating the events. For example, if you want to be notified of events generated by a DB instance, you would set this parameter to db-instance. if this value is not specified, all events are returned. Valid values: ``db-instance``, ``db-cluster``, ``db-parameter-group``, ``db-security-group``, ``db-snapshot``, ``db-cluster-snapshot``.
     */
    @ResourceDiffProperty(updatable = true)
    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * The name of the subscription. (Required)
     */
    public String getSubscriptionName() {
        return subscriptionName;
    }

    public void setSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
    }

    @Override
    protected boolean doRefresh() {
        RdsClient client = createClient(RdsClient.class);

        if (ObjectUtils.isBlank(getSubscriptionName())) {
            throw new BeamException("subscription-name is missing, unable to load db event subscription.");
        }

        try {
            DescribeEventSubscriptionsResponse response = client.describeEventSubscriptions(
                r -> r.subscriptionName(getSubscriptionName())
            );

            response.eventSubscriptionsList().stream()
                .forEach(s -> {
                    setEnabled(s.enabled());
                    setEventCategories(s.eventCategoriesList());
                    setSnsTopicArn(s.snsTopicArn());
                    setSourceIds(s.sourceIdsList());
                    setSourceType(s.sourceType());
                    setArn(s.eventSubscriptionArn());
                }
            );

        } catch (SubscriptionNotFoundException ex) {
            return false;
        }

        return true;
    }

    @Override
    protected void doCreate() {
        RdsClient client = createClient(RdsClient.class);
        CreateEventSubscriptionResponse response = client.createEventSubscription(
            r -> r.enabled(getEnabled())
                    .eventCategories(getEventCategories())
                    .sourceIds(getSourceIds())
                    .sourceType(getSourceType())
                    .subscriptionName(getSubscriptionName())
        );

        setArn(response.eventSubscription().eventSubscriptionArn());
    }

    @Override
    protected void doUpdate(Resource config, Set<String> changedProperties) {
        RdsClient client = createClient(RdsClient.class);
        client.modifyEventSubscription(
            r -> r.enabled(getEnabled())
                    .eventCategories(getEventCategories())
                    .snsTopicArn(getSnsTopicArn())
                    .sourceType(getSourceType())
                    .subscriptionName(getSubscriptionName())
        );
    }

    @Override
    public void delete() {
        RdsClient client = createClient(RdsClient.class);
        client.deleteEventSubscription(
            r -> r.subscriptionName(getSubscriptionName())
        );

    }

    @Override
    public String toDisplayString() {
        return "db event subscription " + getSubscriptionName();
    }
}
